Rspec修正、let, traitの利用
Seungmin0628/rspec_app_exam pull request #1
Opened 2019-12-10 12:42 UTC by SeungMin0628

### 概要
テストケースの不具合を修正
[![Image from Gyazo](https://i.gyazo.com/7946684cf819bd9e12cc5e9a04898251.png)](https://gyazo.com/7946684cf819bd9e12cc5e9a04898251)

### タスクリスト
- [x] TODOの修正
- [x] FIXの修正

2019-12-10 12:55 UTC, yuji91 commented on spec/support/window_macros.rb
> +      yield
この`yield`では実際にはどのような挙動をしますか？

2019-12-10 12:56 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(deadline.strftime('%m/%d %H:%M'))
今回はViewで表示に使われているメソッドがあるので、それを合わせて使った方が良いです！

2019-12-10 12:58 UTC, yuji91 commented on spec/system/task_spec.rb
> +      scenario 'Taskが削除されること' do
こちらのテストケース、個別実行した場合もテストがpassするかを確認して欲しいです！

2019-12-10 13:00 UTC, yuji91 requested changes
featureやscenarioと、describeやitはどちらを使うかは好みもありますが、
一般的にSystemSpecを記載するのであれば describe context it を使った方が良いと思います！

2019-12-13 11:30 UTC, SeungMin0628 commented on spec/support/window_macros.rb
> +      yield
https://github.com/SeungMin0628/rspec_app_exam/pull/1/commits/fd9a6e1e6c9e4a6acbdb673ca1c99536f158b5e3

2019-12-13 11:32 UTC, SeungMin0628 commented on spec/support/window_macros.rb
> +      yield
機能の動作により新しいタブが開く際、
タブに遷移して何かをした後タブを閉じる行為をマクロ化するため、
ブロック機能を利用しました。

リファクタリングして試したところ、上記の仕組みは要らなかったので、消しました！

2019-12-13 11:37 UTC, SeungMin0628 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(deadline.strftime('%m/%d %H:%M'))
https://github.com/SeungMin0628/rspec_app_exam/pull/1/commits/9306759dfaf77d1e8a838c3604131790b85a6fca

2019-12-13 11:41 UTC, SeungMin0628 commented on spec/system/task_spec.rb
> +      scenario 'Taskが削除されること' do
https://github.com/SeungMin0628/rspec_app_exam/pull/1/commits/8ab840e0e8a7c808da1be8c747b85c4815ca1223

2019-12-13 11:45 UTC, SeungMin0628 commented
https://github.com/SeungMin0628/rspec_app_exam/pull/1#pullrequestreview-329815175

下記の記事に剃ってメソッドの名義を変えて書きました。
もう一回ご確認いただけますか？
https://qiita.com/jnchito/items/607f956263c38a5fec24#%E3%83%95%E3%82%A3%E3%83%BC%E3%83%81%E3%83%A3%E3%82%B9%E3%83%9A%E3%83%83%E3%82%AF%E3%81%AE%E3%82%A8%E3%82%A4%E3%83%AA%E3%82%A2%E3%82%B9

2019-12-13 16:55 UTC, yuji91 commented
該当の記事は2015年に作成されたものです。
2019年に更新されていますが、記載の内容は2015年時点のfeature specの記事です。

![image](https://user-images.githubusercontent.com/28836274/70817197-6de31800-1e14-11ea-9737-47da8cdb52d9.png)

2017年にSystemSpecが出ており、公式でFeatureSpecよりSystemSpecが推奨されています。
http://rspec.info/blog/2017/10/rspec-3-7-has-been-released/

そのため、基本的に推奨されているSystemSpecで記載するべきであり、記載もdescribe context itに合わせるべきです。

2019-12-13 17:06 UTC, yuji91 commented on spec/system/task_spec.rb
> +      scenario 'Taskが削除されること' do
FactoryBotのTask.titleが`Task`でなくなったためにこのテストがPassしていると思いますが、ここで意図していたのはページの確認範囲の限定です。
`expect(page).not_to have_content task.title` の pageはページ全体を指しています。
タスクの一覧という範囲だけに確認対象を限定することはできますか？
<img width="800" alt="Screen Shot 2019-12-14 at 2 06 04 AM" src="https://user-images.githubusercontent.com/28836274/70818092-4ee58580-1e16-11ea-84e2-21be27dddd61.png">

2019-12-13 17:07 UTC, yuji91 requested changes
コメントしました。
https://github.com/SeungMin0628/rspec_app_exam/pull/1#issuecomment-565517768
https://github.com/SeungMin0628/rspec_app_exam/pull/1#discussion_r357743084

2019-12-14 04:44 UTC, SeungMin0628 commented on spec/system/task_spec.rb
> +      scenario 'Taskが削除されること' do
https://github.com/SeungMin0628/rspec_app_exam/pull/1/commits/6d371ebad241d9f105e095f2075bb5bdb8bcdcaa

2019-12-14 04:44 UTC, SeungMin0628 commented
https://github.com/SeungMin0628/rspec_app_exam/pull/1#issuecomment-565517768

https://github.com/SeungMin0628/rspec_app_exam/pull/1/commits/f34d4d5b1b1ad1ebe45f2640f7aa722ac96177ad

2019-12-14 07:45 UTC, yuji91 approved these changes
LGTMです！
この感じで応用編の課題ではテストコードも実装お願いします！

2019-12-17 11:37 UTC, merged